[theme]
# Couleur principale (jaune)
primaryColor = "#D97757"

# Couleur de fond de l'application
backgroundColor = "#F0EEE6"

# Couleur de fond secondaire (pour les sidebars)
secondaryBackgroundColor = "#FAF9F5"

# Couleur du texte
textColor = "#141414"

# Police utilisée
font = "sans serif"
